name: AWS cli with Terraform

on:
  release:
    types: [published]

  push:
    branches:
      - master

jobs:
  push_to_registries:
    name: Build image containing both AWS cli and Terraform cli
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.actor }}/aws_cli_with_terraform

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./aws_cli_with_terraform
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


